### ISSUE TITLE
Crash when refreshing tabs.

### ISSUE THREAD

**Issue by NokTham** [gerwaric/acquisition#44]
```
Faulting application name: acquisition.exe, version: 0.11.0.0, time stamp: 0x66739db0
Faulting module name: ucrtbase.dll, version: 10.0.19041.3636, time stamp: 0x81cf5d89
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x43d8
Faulting application start time: 0x01dad943e0efb755
Faulting application path: C:\Users\ZarkBit\AppData\Local\Programs\acquisition\acquisition.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 23fdff51-c03e-40cc-8483-374b5c4c6e2f
Faulting package full name: 
Faulting package-relative application ID: 
```

I'm also not able to expand tabs, not sure why. Any guidance?

**Comment by gerwaric** [comment]
Thank you for this report. Unfortunatelly there is not enough information in what you've included to pinpoint the problem.  It's possible this is related to issues that are being discussed already in https://github.com/gerwaric/acquisition/issues/39.

However, I do have an update with more recent bug fixes. The update also adds automatic crash reporting with a service called BugSplat, so it will be easier to see exactly where in the code crashes are occuring. Here is the link:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1-alpha.7

If you can it a try when you have time, it would be very helpful.

The main issue right now is that version 0.11.0 had a lot of changes to support OAuth. This is needed for acquisition to survive long-term, because OAuth is the only officially documented and supported authentication method for third-party applications. However, with new code comes new bugs, like you've noticed.

If you can try the new version, I do have some time before 3.25 to fix bugs.

**Comment by NokTham** [comment]
Thank you, it's no longer crashing.

**Comment by NokTham** [comment]
Thank you, it's no longer crashing.

**Comment by gerwaric** [comment]
Super! Good luck with 3.25 if you're playing it, and please continue to report any problems with acquisition here.
