### ISSUE TITLE
"Can't update shop -- cannot extract CSRF token from the page"

### ISSUE THREAD

**Issue by NokTham** [gerwaric/acquisition#45]
`ERROR 2024-07-21T02:35:37.709 Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. If you're using Steam to login make sure you use the same login method (steam or login/password) in Acquisition, Path of Exile website and Path of Exile game client. For example, if you created a shop thread while using Steam to log into the website and then logged into Acquisition with login/password it will not work. In this case you should either recreate your shop thread or use a correct login method in Acquisition. `

Not using Steam, tried creating another thread on the forums but keep getting the same error.
Alpha 8

Edit: Logging using poessid allows me to update the thread, but not with oauth.

**Comment by gerwaric** [comment]
Thank you for raising this issue. The problem is that even when you login with OAuth, the POESESSID cookie is needed to update the forum shop threads. There is a settings menu item that lets you do this. I have also added checks to warn the user if the session cookie has not been set:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1-alpha.9

Let me know if that works for you.

**Comment by NokTham** [comment]
Thank you, a9 shows the warning, and setting the POESESSID manually allows the update to go through.
