### ISSUE TITLE
Policy Manager Error

### ISSUE THREAD

**Issue by livejamie** [gerwaric/acquisition#48]
Acquisition isn't working for me and showing this error:

> ERROR 2024-07-23T11:56:02.413 policy manager for "stash-list-request-limit" request 1 reply status was 400 and error was QNetworkReply::ProtocolInvalidOperationError 

I'm logged in via OAuth. It does not show I'm rate limited. Running 11.1-alpha.10

**Comment by gerwaric** [comment]
Hmm. I have not seen that error before. Do you know if the error is repeatable?  Or, if you have time, could you try again in a couple hours to see if it's still a problem?  I'm also curious if it happens in POESESSID mode.

Another thing that would be helpful is if you can set the log level to TRACE using the Settings menu. Then once you get the error, the last couple lines from the log will have a lot more information about that request.  (If you do this, make sure to set the logging level back to INFO or WARN when you are done, because the TRACE level has a ridiculous amount of logging.

One more thought... does your account name or do any of your character name contain any non-ASCII characters?

**Comment by livejamie** [comment]
Thanks for the quick response.

My logging level is already set to trace. The error occurs with both OAuth and Session ID.

![image](https://github.com/user-attachments/assets/993e675b-af2b-4095-ab15-c8b179428b66)

My character names are "livejamie_charactername" no crazy characters.

I rolled back to 0.11.0 and the log is similar

> INFO 2024-07-23T12:33:57.870 Loading item classes from RePoE. 
> INFO 2024-07-23T12:33:58.052 Loading item base types from RePoE. 
> INFO 2024-07-23T12:33:58.296 There are 0 items and 0 tabs after the refresh. 
> INFO 2024-07-23T12:34:08.271 NextSend(): current time is "Tue Jul 23 12:34:08 2024" 
> INFO 2024-07-23T12:34:08.536 NextSend(): current time is "Tue Jul 23 12:34:08 2024" 
> INFO 2024-07-23T12:34:09.062 NextSend(): current time is "Tue Jul 23 12:34:09 2024" 
> ERROR 2024-07-23T12:34:09.063 policy manager for "stash-list-request-limit" request 1 reply status was 400 and error was QNetworkReply::ProtocolInvalidOperationError 
> INFO 2024-07-23T12:34:09.068 NextSend(): current time is "Tue Jul 23 12:34:09 2024" 


I'll try in a couple hours.

**Comment by livejamie** [comment]
FWIW, I just tried [Looty](https://github.com/benjaminjackman/looty) and it picked up my tabs and stash items just fine.

**Comment by gerwaric** [comment]
Thanks for trying a couple things. Does the error happen automatically when the program starts, or do you have to trigger a refresh yourself?

**Comment by livejamie** [comment]
I have to initialize the refresh myself. Nothing happens when I open the program. 

![acquisition_BDxwGsWto9](https://github.com/user-attachments/assets/8e69dc37-442d-4c14-be7b-45831d901785)

**Comment by livejamie** [comment]
I also tried a clean uninstall/reinstall. If there's anything else I can try lmk happy to help.

**Comment by gerwaric** [comment]
I'm thinking about making a special release that crashes when it encounters that error, and then includes acquisition's log in the automatic crash report. Would you be ok giving that a try?

This would let me see exactly what's going on, step by step. It will contain details like your account name and character names, but iwon't contain anything like your session cookie or oauth token. Let  me know if you're comfortable with that.

**Comment by livejamie** [comment]
Yep happy to help!

**Comment by gerwaric** [comment]
Here you go:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1-alpha.10b

That will force the log level to TRACE, and force a hard crash when a network error is encountered, and include the application log file in the crash report. If it works as planned, you should only need to run and crash acquisition once.

**Comment by gerwaric** [comment]
I found the problem. It was GUI bug, and I think I've fixed it:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.1-alpha.11

**Comment by livejamie** [comment]
Excellent work it appears to work as expected now. 

Will let you know if anything else pops up!

**Comment by gerwaric** [comment]
Thanks!

I stumbled across the bug by accident because I wanted to search my stash for some unique jewels to test out a possible league starter. As soon as I saw the `QNetworkReply::ProtocolInvalidOperationError` error message, I instantly forgot what I was doing with my flamewood deadeye and started debugging.
