### ISSUE TITLE
Loading Standard Tabs Causes 100+ Errors and a 24 Hour Ban

### ISSUE THREAD

**Issue by livejamie** [gerwaric/acquisition#56]
This happened to me last week when we were troubleshooting #48 

![image](https://github.com/user-attachments/assets/2d69517d-c389-47c2-8c8b-2e014a027133)

It happens only when I log on to Standard.

Today I logged onto my league account and it worked as expected, but I tried to log onto my Standard account and it showed 120+ errors, something about being unable to parse tabs and the program crashed.

I'm now banned for 24 hours again.

I can't provide any logs because I can't use my SESSID or OpenID to log on to the Path of Exile website.

I'll ask Novynn if they can provide any additional information to help troubleshoot. They said they would pass it along to you.

**Comment by gerwaric** [comment]
You're the second person I'm aware of who was blocked by Cloudflare for this issue. (See https://github.com/gerwaric/acquisition/issues/50). I'm almost certain this was caused by a change introduced in [v0.11.1-alpha.12](https://github.com/gerwaric/acquisition/releases/tag/v0.11.1-alpha.12), made it into the [v0.11.1](https://github.com/gerwaric/acquisition/releases/tag/v0.11.1) release, and was not fixed until [v0.11.1.1](https://github.com/gerwaric/acquisition/releases/tag/v0.11.1.1). See below for details. If I'm right about this, this bug was also the cause of https://github.com/gerwaric/acquisition/issues/51. I have removed the installers and added warnings to all the affected version so that nobody else can accidentally install these versions.

First, I'm sorry.

This bug, like you experienced first-hand, not only impacts people ability to use other third-party tools, it also blocks them from accessing the official website. I introduced this bug while trying to troubleshoot a mysterious crash that turned out to be unrelated, https://github.com/gerwaric/acquisition/issues/49. 

If you want to know what was happening under the hood, here's a summary:

At startup, acquisition doesn't know the status of the API rate limit policies, so it makes special HEAD requests to check the status before making any API calls. These HEAD requests don't count against the rate limit policy, so they are "safe" in one sense. Acquisition was black-listed at the applicaiton level by GGG last year for violating rate limit policies, so I've tried to be very cautious. However, that caution backfired in this case.

The problem was two-fold.

First, acquisition was incorrectly rejecting replies to some of these HEAD requests. Second, if a reply was rejected, acquistion would immediately continue onto the next stash request. This triggered another HEAD request because acquistion was still trying to check the status of the rate limits. However, the reply to this second HEAD request would be incorrectly rejected just like the first. With as many stash tabs as you and other have in Standard, this was causing enough requests to trigger Cloudflar's own rate limit policies. These are different from GGG's rate limit policies, and the Cloudflare policies are undocumented as far as I know, but several hundred or thousand HEAD requests in the span of a few seconds is enough to violate them.

I'm hopeful that this issue has been resolved with v0.11.1.1.

Honestly, the two parts of the problem are both due to my being a rookie c++ web software developer. When acquisition was black-listed for rate limit violations last year, I decided to teach myself enough to solve the problem. Since then, I've been learning more with each issue, but I still have a long way to go and acquisition still needs work, such as the ability to search for pseudo-mods.

**Comment by gerwaric** [comment]
Can I ask if you been able to safely run [v0.11.1.1](https://github.com/gerwaric/acquisition/releases/tag/v0.11.1.1) without being blocked?

**Comment by gerwaric** [comment]
Since this is still an issue with v0.11.1.1, I'm pulling the installer for that version, too, until I can figure out how to address this.

**Comment by gerwaric** [comment]
I found the problem. In addition to the two mistakes I described above, there was a third mistake in how requests were batched at startup. Fixing the first two was necessary, but not enough to prevent this third one from causing the flood of HEAD requests.

I missed this in testing because I only have about 250 tabs in Standard--not enough to trigger Cloudflare. Now that I know what to look for, I can see it happening on my account, too.

**Comment by livejamie** [comment]
Great troubleshooting, and you don't need to be so apologetic! Things happen and I know you're trying your best. :)

**Comment by gerwaric** [comment]
Thanks for being patient. I think I've fixed it, but would love confirmation from someone brave enough to try:

https://github.com/gerwaric/acquisition/releases/tag/v0.11.2-rc.1

**Comment by livejamie** [comment]
My IP has been whitelisted so somebody else with a bunch of tabs would have to try. :)

**Comment by gerwaric** [comment]
Back when I was more panicked this morning, I almost bought a couple hundred tabs just to test it myself :-D

**Comment by livejamie** [comment]
Aw man I hope I didn't cause any unneeded stress on you, I wasn't upset or anything I promise!

**Comment by gerwaric** [comment]
No worries at all. Your issue report was quite useful in helping me figure out what was going on, so I'm happy you filed it!

What worried me was the idea that *everyone* who used acquisition suddently finding themselves blocked from using acquisiton, other tools like awakened trade, and even the trade site. What made it worse is that I had no idea this morning what was going on, because up until your report I was sure I had fixed the issue.

**Comment by Shadetorrent** [comment]
Just dropping by to thank you for your work gerwaric!

**Comment by livejamie** [comment]
It appears to be working as expected for me, but I'd have somebody with a different IP test before closing this out.

![image](https://github.com/user-attachments/assets/b8404b82-eaf3-4030-8051-bad9a45848e9)

**Comment by gerwaric** [comment]
@Shadetorrent thank you!  Hopefully the 0.11.2-rc.1 release is stable for a while, so I can get back to my league starter  :-)

@livejamie good to hear. I'll close this ticket and push out 0.11.2 as a final release in a couple days if nothing else shows up.

A bunch of the recent issues were due to rate limiting and OAuth. Now that those are doing, I'm planning to work on a couple minor features, then maybe tackle some bigger stuff like pseudo-mods and internal database rework towards the end of the league.

**Comment by livejamie** [comment]
It got to ~300 tabs and then errored out. I don't know if this would have resulted in a rate limit for a regular IP. You can ask Novynn.

```
Errors and warnings will be printed here
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "Card (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "Card (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "Card (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "Card (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "~price 1.5 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "~price 2.5 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "~price 4.9999 divine (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "$$$" colour: "4d00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "~price 2.99999 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "~price 3.9999 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "~price 4.9999 divine (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "Card (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.761 Cannot parse the stash tab "Card (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "~price 3 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "~price 4 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "~price 5 divine (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "MA (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "Card" colour: "bf00" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "~price 1.5 chaos (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "~price 3 divine (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "~price 5 divine (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "Essence (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "CA (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.763 Cannot parse the stash tab "FR (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "Breach (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 3 exalted (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 4 exalted (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 5 exalted (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 20 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 25 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 30 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 35 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 40 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 50 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "CA (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 75 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 1.5 exalted (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "FR (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 3 exalted (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 4 exalted (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "~price 5 exalted (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "meat shields (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "Smite (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "EA (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "DC (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.764 Cannot parse the stash tab "FR (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "Cluster (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "CR (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "$$ (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "D1 (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "D2 (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "FO (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "ME (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.765 Cannot parse the stash tab "D3 (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "S (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "U (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "C (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "C (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "BL (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "F (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "E (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "BS (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "E (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "F (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "~price 3 alch (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "Brains (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "~price 2 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "Eyes (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "CT1 (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "~price 3 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "~price 3 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "CT2 (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "Hearts (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "F (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "DO (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "Livers (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "~price 1 alch (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.766 Cannot parse the stash tab "I1 (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 1 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "Dump (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 2 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 3 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 5 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "I5 (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 7 chaos (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "Flasks (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "Soulrend (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "PR (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "~price 5 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.767 Cannot parse the stash tab "Bug (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "DE (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "M (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "Crafting (Remove-only)" colour: "bf00" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "Private/Leveling (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "~price 1 alch (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "~price 1 alch (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "Loreweave (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "~price 1 gcp (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "ES Gear (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "Private (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.768 Cannot parse the stash tab "~price 3 chisel (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "Ice Golem (Remove-only)" colour: "ff" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "Necro (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "Talismans (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "Private (Remove-only)" colour: "80" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "~b/o 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "~b/o 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "~b/o 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "~b/o 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "~b/o 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "~b/o 1 chaos (Remove-only)" colour: "4d00" 
ERROR 2024-08-02T07:09:10.769 Cannot parse the stash tab "Graveyard (Remove-only)" colour: "80" 
ERROR 2024-08-02T08:00:45.400 Received a reply for "stash-request-limit" without rate limit headers. 
```

**Comment by gerwaric** [comment]
@livejamie I don't think those errors would have results in a rate-limit violation, but there's something strange about that last one, so it's possible. If you have time, could you copy and paste the 10-20 lines from your log file leading up to that error message:

> ERROR 2024-08-02T08:00:45.400 Received a reply for "stash-request-limit" without rate limit headers

The other messages about parsing the color should be warnings at best. That's because the stash tab colour field is defined as having 6 digits in the current documentation, but on some legacy tabs it's 2 or 4 digits, so acquisition ignores the colors of those tabs. I'll change them in the next RC.

**Comment by livejamie** [comment]
I gave it a shot tonight and it appears to be working as expected.

![image](https://github.com/user-attachments/assets/dcd6e6c8-b235-4be8-9351-68ec2c18b0db)

**Comment by gerwaric** [comment]
Glad to hear it!

I'm planning to add the ability to update the list of stash tabs and characters without updating their contents, since just updating the lists will be almost instant.

However, I'm waiting until I can get more of the bugs people are reporting now fixed before adding features.
